# fly.toml app configuration file generated for super-dice-roll-clj on 2023-05-29T13:44:04-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "super-dice-roll-clj"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
