version: "3.7"

services:
  db-rolls:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-rolls-data:/var/lib/postgresql/data

  db-rolls-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@pg.cc
      PGADMIN_DEFAULT_PASSWORD: pg
    ports:
      - "5433:80"

volumes:
  db-rolls-data:
